name: Go Build and Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6'

jobs:
  build-go:
    runs-on: ubuntu-latest
    env:
      FILE_NAME: hello-server
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Go for Linux
      run: go build $FILE_NAME.go

    - name: Build Go for Windows
      run: GOOS=windows GOARCH=amd64 go build $FILE_NAME.go
      shell: bash

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v3
      with:
        name: linux
        path: hello-server

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: hello-server.exe

  download-and-run-linux:
    runs-on: ubuntu-latest
    needs: build-go
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Linux Artifact
      uses: actions/download-artifact@v3
      with:
        name: linux

    - name: Run Script
      run: |
        chmod +x ./run.sh
        ./run.sh

  download-only-windows:
    runs-on: windows-latest
    needs: build-go
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Windows Artifact
      uses: actions/download-artifact@v3
      with:
        name: windows
